name: practice_ai_front_demo
description: 私人管家 - 个人日程管理与记账APP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.2.0

  # Dependency Injection
  get_it: ^7.7.0

  # Networking
  dio: ^5.4.3+1

  # Local Storage
  flutter_secure_storage: ^9.2.2

  # Notifications
  flutter_local_notifications: ^17.2.1+2

  # Charts
  fl_chart: ^0.68.0

  # Image Picker
  image_picker: ^1.1.2

  # Utilities
  intl: ^0.20.2
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  flutter_secure_storage_web: ^1.2.1
  shared_preferences_web: ^2.4.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/icons/
